- name: Setup prompt
  ansible.builtin.shell: set-prompt {{ tool_name }}

- name : Create github local user
  ansible.builtin.user:
    name: github

- name : Create github actions folder
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: github
    group: github

- name : Download github runner
  ansible.builtin.unarchieve:
    src: https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz
    dest: /actions-runner
    owner: github
    grup: github
    remote_src: yes